# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 03:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_merchant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
    ]
