# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
        ('cart', '0004_auto_20160120_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='merchant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='merchants.Merchant'),
        ),
    ]
