# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20160107_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='menu_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.MenuCategory'),
        ),
    ]
